INHERIT: ./user-documentation/data/configs/ospool.yml

docs_dir: ./user-documentation/data/docs/ospool

site_name: OSPool Documentation
site_url: "https://portal.osg-htc.org/documentation/"
repo_name: osg-htc/user-documentation
theme:
  features:
    - navigation.tabs
  name: material
  logo: assets/OSG_Logo.svg
  favicon: assets/OSG_Logo.svg
  custom_dir: overrides

markdown_extensions:
  - admonition
  
  - meta
  - pymdownx.details
  - toc:
      permalink: True
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/code-highlight.css
  - stylesheets/osg.css
